### ISSUE TITLE
表格添加参数autoIgnorePagination运行出错

### ISSUE THREAD

**Issue by limmyforget** [CNFeffery/feffery-antd-components#10]
请问我这样写对么，怎么运行的时候提示received an unexpected keyword argument: `autoIgnorePagination`
代码如下：
```
fac.AntdTable(
    columns=[
        {
            'title': '列1',
            'dataIndex': "列1索引"
        },
        {
            'title': '列2',
            'dataIndex': '列2索引'
        }
    ],
    data=[
        {
            '列1索引': i,
            '列2索引': i
        }
        for i in range(5)
    ],
    autoIgnorePagination=True
)
```

**Comment by CNFeffery** [comment]
> 请问我这样写对么，怎么运行的时候提示received an unexpected keyword argument: `autoIgnorePagination` 代码如下：
> 
> ```
> fac.AntdTable(
>     columns=[
>         {
>             'title': '列1',
>             'dataIndex': "列1索引"
>         },
>         {
>             'title': '列2',
>             'dataIndex': '列2索引'
>         }
>     ],
>     data=[
>         {
>             '列1索引': i,
>             '列2索引': i
>         }
>         for i in range(5)
>     ],
>     autoIgnorePagination=True
> )
> ```

@limmyforget 你好 这个参数其实0.0.1rc7中已经移除了，相同的功能变更为pagination下的hideOnSinglePage参数来控制了，官方文档我今天下午刚刚发现这个遗留错误，已经修改

**Comment by limmyforget** [comment]
> > 请问我这样写对么，怎么运行的时候提示received an unexpected keyword argument: `autoIgnorePagination` 代码如下：
> > ```
> > fac.AntdTable(
> >     columns=[
> >         {
> >             'title': '列1',
> >             'dataIndex': "列1索引"
> >         },
> >         {
> >             'title': '列2',
> >             'dataIndex': '列2索引'
> >         }
> >     ],
> >     data=[
> >         {
> >             '列1索引': i,
> >             '列2索引': i
> >         }
> >         for i in range(5)
> >     ],
> >     autoIgnorePagination=True
> > )
> > ```
> 
> @limmyforget 你好 这个参数其实0.0.1rc7中已经移除了，相同的功能变更为pagination下的hideOnSinglePage参数来控制了，官方文档我今天下午刚刚发现这个遗留错误，已经修改

哦，好的，谢谢，我去试试
