### ISSUE TITLE
locale 'en-us' not working on AntdUpload

### ISSUE THREAD

**Issue by DarkCTO** [CNFeffery/feffery-antd-components#108]
fac.AntdUpload(locale='en-us', apiUrl='/upload')

And my component is still in chinese.

![2023-10-20-110847_223x84_scrot](https://github.com/CNFeffery/feffery-antd-components/assets/99158109/22282090-ac0b-4dba-b06a-5cfe4c75f4f4)

**Comment by CNFeffery** [comment]
@DarkCTO Custom `buttonContent` for `AntdUpload`

**Comment by DarkCTO** [comment]
Yeah, but the notifications are still in chinese.

**Comment by CNFeffery** [comment]
fix in `0.2.10`.
