### ISSUE TITLE
Full String Length in AntdSelect

### ISSUE THREAD

**Issue by DarkCTO** [CNFeffery/feffery-antd-components#112]
![2023-10-27-105331_490x388_scrot](https://github.com/CNFeffery/feffery-antd-components/assets/99158109/69cc05fa-5d5a-47ef-8b65-c90aef456cb0)

![2023-10-27-105425_329x396_scrot](https://github.com/CNFeffery/feffery-antd-components/assets/99158109/02d28d65-22cb-4e65-a1f4-54544caa4573)

I have some entries that are very long, would there be options to display in full like in ChartStudio?

**Comment by CNFeffery** [comment]
@DarkCTO Refer to the example below:

![image](https://github.com/CNFeffery/feffery-antd-components/assets/49147660/66657f06-3a92-4cc6-850b-d0dfde0ec9f3)

```python
import dash
from dash import html
import feffery_antd_components as fac
import feffery_utils_components as fuc

app = dash.Dash(__name__)

app.layout = html.Div(
    [
        fuc.FefferyStyle(
            rawStyle='''
.ant-select-item-option-content {
    white-space: pre-wrap;
    word-wrap: break-word;
    overflow: hidden;
}
'''
        ),
        fac.AntdSelect(
            options=[
                {
                    'label': html.Div(
                        f'value{i}'*5*i
                    ),
                    'value': f'value{i}'
                }
                for i in range(1, 6)
            ],
            style={
                'width': 200
            }
        ),
    ],
    style={
        'padding': 50
    }
)

if __name__ == '__main__':
    app.run(debug=True)

```
