### ISSUE TITLE
Getting 'clickedKey' from Right-click custom context menu 

### ISSUE THREAD

**Issue by Christian-SWS** [CNFeffery/feffery-antd-components#115]
Dear Feffery-antd-components community,

I want to create a right click context menu by clicking on a Plotly plot within my Dash App in the end.
I found the very helpful tutorial from CNFeffery (https://fac.feffery.tech/AntdDropdown) which demonstares how to achieve a custom made context menu by a right click within a FefferyDiv. That works pretty well. 
The fac.AntdDropdown is stored within an html.Div in that case. 

I was now wondering how I can get the "clickedKey" from my context menu (the fac.AntdDropdown)  to use it within another callback function. I can only trigger a callback function by the "contextMenuEvent" which is the rigth click on the FefferyDiv but not after clicking an option from the context menu. 

Looking forward for any suggestions and help! 

Here is a minmal code example:

import dash
from dash import html
import feffery_utils_components as fuc
import feffery_antd_components as fac
from dash.dependencies import Input, Output
import uuid

app = dash.Dash(__name__)

app.layout = html.Div(
    [
            fuc.FefferyDiv(
                        'Dropdown Area',
                        id='dropdown-free-position-demo-trigger',
                        enableListenContextMenu=True,
                        style={
                            'borderRadius': 6,
                            'background': '#adb5bd',
                            'height': 400,
                            'color': 'white',
                            'display': 'flex',
                            'justifyContent': 'center',
                            'alignItems': 'center'
                        }
                    ),
                
        html.Div(id='dropdown-free-position-demo-container'),
    ],
    style={
        'padding': 50
    }
)

@app.callback(
    Output('dropdown-free-position-demo-container', 'children'),
    Input('dropdown-free-position-demo-trigger', 'contextMenuEvent'),
    prevent_initial_call=True
)
def dropdown_free_position_demo(contextMenuEvent):

    if contextMenuEvent:

        context =  fac.AntdDropdown(
            #key=str(uuid.uuid4()),# DISSABLED as it caused a "Warning: nr: `key` is not a prop." in my browser console
            visible=True,
            freePosition=True,
            freePositionStyle={
                'left': contextMenuEvent['clientX'],
                'top': contextMenuEvent['clientY']
            },
            menuItems=[
                {
                    'title': f'Option{i}',
                    'key': f'key{i}'
                }
                for i in range(1, 6)
            ],
            trigger='click'
        )
        return context

if __name__ == '__main__':
    app.run(debug=True)

**Comment by CNFeffery** [comment]
@Christian-SWS refer to this example:
![image](https://github.com/CNFeffery/feffery-antd-components/assets/49147660/9e7bb44f-4a2b-4a56-88ad-c265a0d7f43b)

```python
import json
import uuid
import dash
from dash import html
import feffery_utils_components as fuc
import feffery_antd_components as fac
from dash.dependencies import Input, Output, ALL

app = dash.Dash(__name__)

app.layout = html.Div(
    [
        fuc.FefferyDiv(
            'Dropdown Area',
            id='dropdown-free-position-demo-trigger',
            enableListenContextMenu=True,
            style={
                'borderRadius': 6,
                'background': '#adb5bd',
                'height': 400,
                'color': 'white',
                'display': 'flex',
                'justifyContent': 'center',
                'alignItems': 'center'
            }
        ),

        html.Div(id='dropdown-free-position-demo-container'),
        html.Pre(
            id='show-event'
        )
    ],
    style={
        'padding': 50
    }
)


@app.callback(
    Output('dropdown-free-position-demo-container', 'children'),
    Input('dropdown-free-position-demo-trigger', 'contextMenuEvent'),
    prevent_initial_call=True
)
def dropdown_free_position_demo(contextMenuEvent):

    if contextMenuEvent:

        context = fac.AntdDropdown(
            id={
                'type': 'current-dropdown',
                'index': str(uuid.uuid4())
            },
            visible=True,
            freePosition=True,
            freePositionStyle={
                'left': contextMenuEvent['clientX'],
                'top': contextMenuEvent['clientY']
            },
            menuItems=[
                {
                    'title': f'Option{i}',
                    'key': f'key{i}'
                }
                for i in range(1, 6)
            ],
            trigger='click',
            nClicks=0
        )
        return context


@app.callback(
    Output('show-event', 'children'),
    [
        Input(
            {
                'type': 'current-dropdown',
                'index': ALL
            },
            'nClicks'
        ),
        Input(
            {
                'type': 'current-dropdown',
                'index': ALL
            },
            'clickedKey'
        ),
    ],
    prevent_initial_call=True
)
def collect_dropdown_event(nClicks, clickedKey):

    # Using appropriate conditional statements to capture the actual right-click menu event
    if nClicks and clickedKey and clickedKey[0]:
        return json.dumps(
            dict(
                nClicks=nClicks[0],
                clickedKey=clickedKey[0]
            ),
            indent=4
        )

    return dash.no_update


if __name__ == '__main__':
    app.run(debug=True)

```

**Comment by Christian-SWS** [comment]
Thank you very much for this fast response! 
That solved my problem!!
