### ISSUE TITLE
支持 persistence

### ISSUE THREAD

**Issue by kikyous** [CNFeffery/feffery-antd-components#12]
https://dash.plotly.com/persistence#for-component-developers

**Comment by CNFeffery** [comment]
感谢提醒，我会在近期对涉及到用户输入的组件进行persistence功能追加

**Comment by CNFeffery** [comment]
@kikyous 已针对适合的组件相关属性添加持久化功能，具体列表见：

https://github.com/CNFeffery/feffery-antd-components#6-%E8%BF%91%E6%9C%9Ftodo%E8%AE%A1%E5%88%92
