### ISSUE TITLE
对我这个小白开说这个lib很友好，请教一下一些底层显示支持英文吗

### ISSUE THREAD

**Issue by guowei0419** [CNFeffery/feffery-antd-components#13]
比如，AntdTable中的filter功能，如果输入一个不存在的选项，会显示暂无数据；
AntdDateRangePicker中 week的使用，默认显示就是2021 37周，这个周支持英文显示吗
多谢！

**Comment by CNFeffery** [comment]
> 比如，AntdTable中的filter功能，如果输入一个不存在的选项，会显示暂无数据； AntdDateRangePicker中 week的使用，默认显示就是2021 37周，这个周支持英文显示吗 多谢！

之前我在开发`fac`时一直没有想过英文版本的事，不过之后的版本可以添加语言设置功能，比如说先对`中/英文切换`进行支持

**Comment by guowei0419** [comment]
> > 比如，AntdTable中的filter功能，如果输入一个不存在的选项，会显示暂无数据； AntdDateRangePicker中 week的使用，默认显示就是2021 37周，这个周支持英文显示吗 多谢！
> 
> 之前我在开发`fac`时一直没有想过英文版本的事，不过之后的版本可以添加语言设置功能，比如说先对`中/英文切换`进行支持

感谢，因为我看code中函数 和变量名字用的英文都很正宗，就是个别提示是中文的， 期待更新

**Comment by CNFeffery** [comment]
@guowei0419 仓库最新开发版本针对部分涉及多语言状态的组件已添加参数`locale`，默认`zh-cn`为中文简体，可选`en-us`英文状态，示例：

```python
fac.AntdDatePicker(),
fac.AntdDateRangePicker(),

fac.AntdDatePicker(locale='en-us'),
fac.AntdDateRangePicker(locale='en-us')
```

![image](https://user-images.githubusercontent.com/49147660/147398516-03e43a47-5f36-4e02-a10a-85be951b5421.png)


具体支持国际化参数的组件见：
https://github.com/CNFeffery/feffery-antd-components#6-%E8%BF%91%E6%9C%9Ftodo%E8%AE%A1%E5%88%92

**Comment by guowei0419** [comment]
> @guowei0419 仓库最新开发版本针对部分涉及多语言状态的组件已添加参数`locale`，默认`zh-cn`为中文简体，可选`en-us`英文状态，示例：
> 
> ```python
> fac.AntdDatePicker(),
> fac.AntdDateRangePicker(),
> 
> fac.AntdDatePicker(locale='en-us'),
> fac.AntdDateRangePicker(locale='en-us')
> ```
> 
> ![image](https://user-images.githubusercontent.com/49147660/147398516-03e43a47-5f36-4e02-a10a-85be951b5421.png)
> 
> 具体支持国际化参数的组件见： https://github.com/CNFeffery/feffery-antd-components#6-%E8%BF%91%E6%9C%9Ftodo%E8%AE%A1%E5%88%92

感谢更新，回调使用的start date 和end date好像也对应改了， 正在研究怎么用起来， 另外更新FAC到开发板之后，run app（debug=False）， 主页一直没有任何显示和反应，改成debug=True之后，可以正常显示，不知道为什么

**Comment by CNFeffery** [comment]
> > @guowei0419 仓库最新开发版本针对部分涉及多语言状态的组件已添加参数`locale`，默认`zh-cn`为中文简体，可选`en-us`英文状态，示例：
> > ```python
> > fac.AntdDatePicker(),
> > fac.AntdDateRangePicker(),
> > 
> > fac.AntdDatePicker(locale='en-us'),
> > fac.AntdDateRangePicker(locale='en-us')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/49147660/147398516-03e43a47-5f36-4e02-a10a-85be951b5421.png)
> > 具体支持国际化参数的组件见： https://github.com/CNFeffery/feffery-antd-components#6-%E8%BF%91%E6%9C%9Ftodo%E8%AE%A1%E5%88%92
> 
> 感谢更新，回调使用的start date 和end date好像也对应改了， 正在研究怎么用起来， 另外更新FAC到开发板之后，run app（debug=False）， 主页一直没有任何显示和反应，改成debug=True之后，可以正常显示，不知道为什么

@guowei0419 是的，我最近就在编写文档，为`0.0.1rc8`版本做准备，你说的debug=False后不显示，是不是`dash.Dash()`里设置了`serve_locally=False`，这个只有正式版才有`unpkg`的镜像源可以用，否则会因为`feffery-antd-components.min.js`静态资源加载失败而导致应用渲染失败，可以浏览器开发者工具加载时看一下`network`面板是不是有红色的失败加载内容
