### ISSUE TITLE
aria-* data-* 传参支持

### ISSUE THREAD

**Issue by yzcheung** [CNFeffery/feffery-antd-components#148]
希望fac组件允许类似dash的html组件aria-* data-*的方式传参

**Comment by CNFeffery** [comment]
@yzcheung `fac`大于等于`0.3.0rc11`版本可用，通过字典拆包进组件，示例：
![image](https://github.com/CNFeffery/feffery-antd-components/assets/49147660/03d95188-0363-4f81-878c-c2baffb99093)
