### ISSUE TITLE
可否开发一个类似React Flow的节点图组件？

### ISSUE THREAD

**Issue by vnnw** [CNFeffery/feffery-antd-components#15]
譬如集成 https://reactflow.dev/ ，可以方便的做工作流？

**Comment by CNFeffery** [comment]
@vnnw 感谢提供新的功能开发思路，这个我是有开发计划的，但会作为独立的框架开展开发计划，不会包含在当前的`fac`框架中，我会多方面比较reactflow与antv x6之间的优劣情况，选择合适的作为二次开发的依赖

**Comment by vnnw** [comment]
感谢回复。
非常期待。
目前有预计上线时间吗？

**Comment by CNFeffery** [comment]
@vnnw 暂时没有，因为目前业余时间主要放在对`fac`文档的编写及测试上，后续有更新消息我会在这个issues下@你
