### ISSUE TITLE
Full height aside bar

### ISSUE THREAD

**Issue by josepaulo1233** [CNFeffery/feffery-antd-components#155]
Hi, there's a way to set aside bar with full height along the page (complete the red lines in figure)? 

<img width="53" alt="image" src="https://github.com/CNFeffery/feffery-antd-components/assets/26235308/f1a8be0a-e35d-4536-aa72-2e8b8c915b4f">

`
def sidebar():

    sidebar = html.Div([

            html.Div(
                [
                    fac.AntdLayout(
                        [
                            fac.AntdAffix(
                            fac.AntdSider(
                                [
                                    fac.AntdButton(
                                        id='menu-collapse-sider-custom-demo-trigger',
                                        icon=fac.AntdIcon(
                                            id='menu-collapse-sider-custom-demo-trigger-icon',
                                            icon='antd-arrow-left',
                                            style={
                                                'fontSize': '14px',
                                            }
                                        ),
                                        shape='circle',
                                        type='text',
                                        style={
                                            'position': 'absolute',
                                            'zIndex': 1,
                                            'top': 25,
                                            'right': -13,
                                            'boxShadow': 'rgb(0 0 0 / 10%) 0px 4px 15px 0px',
                                            'background': 'white'
                                        }
                                    ),

                                    fac.AntdMenu(
                                        menuItems=[
                                            {
                                                'component': 'Item',
                                                'props': {
                                                    'key': f'{str(title)}',
                                                    'title': title,
                                                    'icon': icon,
                                                    'href': link,
                                                    #'target': '_',
                                                }
                                            }
                                            for icon, link, title in zip(icons, links, titles)
                                        ],
                                        mode='vertical',
                                        defaultSelectedKey=titles[0],
                                        style={
                                            'height': '100%',
                                            #'fontSize': '11px',
                                            'overflow': 'hidden auto',
                                            'background-color': 'white', 
                                        },
                                        
                                        #inlineCollapsed=True
                                    )
                                ],
                                id='menu-collapse-sider-custom-demo',
                                collapsible=True,
                                collapsedWidth=60,
                                trigger=None,
                                style={'background': 'white', 'height': '100%'}

                            ),  style={'background': 'white', }),

                            fac.AntdContent(
                                children=dash.page_container,
                                style={
                                    'background': 'white',
                                    'padding': '10px'
                                }
                            )
                        ],
                        style={
                            'height': '100%'
                        }
                    )
                ],
                style={
                    'height': '100%',
                    'border': '1px solid rgb(241, 241, 241)',  
                }
    )])
    
    return sidebar
`

thanks

**Comment by CNFeffery** [comment]
@josepaulo1233 You can refer to the following layout examples:

https://github.com/CNFeffery/dash-master/tree/main/%E5%8E%86%E5%8F%B2%E6%96%87%E7%AB%A0/Dash%E5%BA%94%E7%94%A8%E9%A1%B5%E9%9D%A2%E6%95%B4%E4%BD%93%E5%B8%83%E5%B1%80%E6%8A%80%E5%B7%A7/demo-apps
