### ISSUE TITLE
AntdTable除了maxHeight参数调整以外有什么方式让我的表格无论在多大分辨率的显示器上都占满吗

### ISSUE THREAD

**Issue by YuMingtao0503** [CNFeffery/feffery-antd-components#170]

**Comment by CNFeffery** [comment]
@YuMingtao0503 那你可以配合`fuc`里的`FefferyWindowSize`，通过回调监听动态设置`AntdTable`的`maxHeight`

https://fuc.feffery.tech/FefferyWindowSize
