### ISSUE TITLE
AntdCollapse的is_open不能通过回调改变状态

### ISSUE THREAD

**Issue by QHQIII** [CNFeffery/feffery-antd-components#18]

**Comment by CNFeffery** [comment]
@QHQIII 因为这个组件我设计它就是用来做静态内容展示的，你可以描述一下你是在怎样的场景下，需要用它来做回调交互吗

**Comment by QHQIII** [comment]
我是先从dbc的折叠组件看过来的，它是通过主动is_open这个的设定控制开关，但是动画有些卡顿。
我是在做数据预处理筛选的时候用到的，这一部分很长，传入数个路径通过设置拒绝字段和准入字段来匹配输出一个筛选列表，而且还包裹了一个穿梭框作为二次筛选，占据的页面很多，但是我又在下面提供了一个输入栏，可以直接输入一个文件的路径，供处理部分使用，这二者是二选一的，我用一个开关控制，当为直选的时候就像把上面的部分隐藏或者冻结掉，dash的hidden没有动画，dbc的折叠有点卡，fac里面没合适的组件提供disable，我就想用AntdCollapse来处理了

**Comment by CNFeffery** [comment]
@QHQIII 最新开发版本中`is_open`已可控，请参考当前仓库中`usage.py`中的相关例子
