### ISSUE TITLE
Radio组件defaultValue参数问题

### ISSUE THREAD

**Issue by yzcheung** [CNFeffery/feffery-antd-components#186]
`import feffery_antd_components.alias as fac
from dash import Dash, Input, Output, html
from dash.exceptions import PreventUpdate

app = Dash(__name__)

app.layout = html.Div(
    [
        html.Div(id="notification"),
        fac.RadioGroup(
            id="radio",
            options=[{"label": value, "value": value} for value in ["A", "B", "C"]],
            defaultValue="A",
        ),
    ]
)

@app.callback(
    Output("notification", "children"), Input("radio", "value"), prevent_initial_call=True
)
def listen(value):
    if value:
        return fac.Message(content=value, type="success")
    raise PreventUpdate

if __name__ == "__main__":
    app.run(debug=True)
`

fac版本0.3.0rc24
prevent_initial_call未按照预期阻止回调

**Comment by CNFeffery** [comment]
这是必然的，因为底层初始化会自动进行一次从`defaultValue`->未定义`value`的更新，你可以直接使用`value`参数来赋默认值
