### ISSUE TITLE
文档中AntdAlert的辅助文本参数description未设置

### ISSUE THREAD

**Issue by QHQIII** [CNFeffery/feffery-antd-components#19]
AntdAlert的辅助文本在文档中说明为参数description，但是组件事实上没有这个参数，辅助文本是直接给字符串，事实上是作为children传入的

**Comment by CNFeffery** [comment]
@QHQIII 感谢提醒😀，这个纰漏我会在正在编写中的`0.0.1rc8`版本文档中进行修正

**Comment by CNFeffery** [comment]
@QHQIII 已修复，去试试`0.0.1rc8`版本中的相关功能吧

**Comment by QHQIII** [comment]
新文档中组件AntdDropdown的按钮模式示例代码漏掉了buttonMode的设定哦

还有一点请问AntdPageHeader的ghost是控制什么呢？

**Comment by CNFeffery** [comment]
- [x] `AntdDropdown`文档遗漏部分已修复
- [x] `AntdCountdown`从`AntdSStatistic`抄过来的参数说明已替换“统计数值”为“倒计时”
- [x] `AntdTypography`和`AntdLink`是早期设计的组件，后来发现很鸡肋后面就没开发，已从`README`中删除
- [x] `AntdPageHeader`中的`ghost`参数说明已补上
- [x] `AntdRate`的颜色可以通过自定义外部css来实现，示例：
```css
.ant-rate {
    color: red !important;
}
```
![image](https://user-images.githubusercontent.com/49147660/152315181-c8b4b29e-51b1-40e7-ad41-236e3ae88e33.png)
