### ISSUE TITLE
增加StyleProvider组件

### ISSUE THREAD

**Issue by yzcheung** [CNFeffery/feffery-antd-components#190]
Ant Design 从 5.17.0 起支持配置 layer 进行统一降权。经过降权后，antd 的样式将始终低于默认的 CSS 选择器优先级，以便于用户进行样式覆盖。
相关链接：https://ant.design/docs/react/compatible-style-cn

**Comment by CNFeffery** [comment]
@yzcheung 你目前遇到的具体问题场景有例子吗

**Comment by yzcheung** [comment]
使用tailwindcss在ConfigProvider中设置compatibilityMode为True时样式仍然会出现奇怪的兼容问题，目前tailwindcss和ant design样式兼容的官方解决方案是在StyleProvider中进行layer降权，详情参照：https://github.com/ant-design/ant-design/issues/38794#issuecomment-2208999633

或者可以在ConfigProvider中额外增加layer降权的参数。

**Comment by CNFeffery** [comment]
@yzcheung 那针对`StyleProvider`启用`layer`，与原本的`compatibilityMode`效果是需要组合使用，还是二选一的模式

**Comment by CNFeffery** [comment]
fac>=0.3.0rc26可用，参考示例：
![image](https://github.com/user-attachments/assets/23d03f0d-33c0-483f-8877-78770c002efe)
