### ISSUE TITLE
可以弄一个富文本框的组件么

### ISSUE THREAD

**Issue by limmyforget** [CNFeffery/feffery-antd-components#2]
在dash中配置富文本框有点麻烦，尤其是上传图片，可不可以封装一个富文本框的组件，让我们可以用python语句配置图片上传路径就可以了，谢谢！

**Comment by CNFeffery** [comment]
@limmyforget 你说的是富文本编辑器吧  那个不在我当前这个项目的计划中，但是可以作为另外的dash组件库的灵感来源，如果你有推荐的基于react的富文本编辑器可以推荐给我，只要是基于react的我都可以想办法开发成dash组件😇

**Comment by limmyforget** [comment]
> 
> 
> @limmyforget 你说的是富文本编辑器吧 那个不在我当前这个项目的计划中，但是可以作为另外的dash组件库的灵感来源，如果你有推荐的基于react的富文本编辑器可以推荐给我，只要是基于react的我都可以想办法开发成dash组件innocent

谢谢，是富文本框编辑器，期待大佬开发，这对于小白太有用了。
