### ISSUE TITLE
小白问题，AntdDraggerUpload上传文件后，如何读取文件，文件默认存储在哪

### ISSUE THREAD

**Issue by guowei0419** [CNFeffery/feffery-antd-components#21]

**Comment by guowei0419** [comment]
![image](https://user-images.githubusercontent.com/8343045/154789467-a2a4fd18-a455-4fbb-85b9-1de26c40cea4.png)
自动生成文件夹，但是没有文件

**Comment by CNFeffery** [comment]
@guowei0419 因为我官网的例子为了节省带宽，并没有真的把你们上传的文件存到本地，写出到本地的部分被我注释掉了
![image](https://user-images.githubusercontent.com/49147660/154798238-06e387db-7d15-4807-905e-e93cebfd235d.png)

**Comment by guowei0419** [comment]
> @guowei0419 因为我官网的例子为了节省带宽，并没有真的把你们上传的文件存到本地，写出到本地的部分被我注释掉了 ![image](https://user-images.githubusercontent.com/49147660/154798238-06e387db-7d15-4807-905e-e93cebfd235d.png)

多谢指导！
