### ISSUE TITLE
AntdConfigProvider different locales

### ISSUE THREAD

**Issue by deadkex** [CNFeffery/feffery-antd-components#212]
Is it possible to remove this limitation? And for example import the external_scripts & external_stylesheets manually?
https://github.com/CNFeffery/feffery-antd-components/blob/286750f5dd3a154972b53699d4fadb698eb756a1/src/lib/components/other/AntdConfigProvider.react.js#L193

**Comment by CNFeffery** [comment]
@deadkex Language packs can only be introduced during the underlying build package, which additional language you want to implement?

**Comment by deadkex** [comment]
@CNFeffery I would like to have german translations

**Comment by CNFeffery** [comment]
@deadkex Are you interested in contributing some language translation content? In addition to the direct application of the fac official language package, some secondary development features are additional written translation parameters.

**Comment by CNFeffery** [comment]
@deadkex It's easy, you can only add `de_de` translations for the `locale2text` in https://github.com/CNFeffery/feffery-antd-components/blob/main/src/lib/components/locales.react.js , then create a pr, I will complete the rest code changes on other places.

**Comment by deadkex** [comment]
https://github.com/CNFeffery/feffery-antd-components/pull/215

**Comment by CNFeffery** [comment]
@deadkex available from `0.3.3`: https://github.com/CNFeffery/feffery-antd-components/releases/tag/0.3.3
