### ISSUE TITLE
Website is down or not loading pages

### ISSUE THREAD

**Issue by michaelrussell4** [CNFeffery/feffery-antd-components#213]
The website isn't loading the data for the pages. The sidebar nav works correctly but the pages just aren't loading. Just a blank screen. Tried on Brave and Chrome browsers. 

Image showing attempt to go to https://fac.feffery.tech/AntdSteps

![image](https://github.com/user-attachments/assets/557c768f-aac1-4d14-ac7e-5ec5caa3a09c)

**Comment by CNFeffery** [comment]
@michaelrussell4 fixed, I am testing the internationalized document switching function, and some translated files are still to be built, later today, I will introduce in detail how to contribute English documents for the fac official website in https://github.com/CNFeffery/feffery-antd-docs/issues/166.

**Comment by CNFeffery** [comment]
The documentation page of AntdButton ( https://fac.feffery.tech/AntdButton ) has currently completed the function demonstration of bilingual switching between Chinese and English.
