### ISSUE TITLE
求问怎么在AntdTable展示url连接的图片

### ISSUE THREAD

**Issue by wjlyclll** [CNFeffery/feffery-antd-components#22]
目前只知道dash_table.DataTable中可以通过设置columns的presentation为markdown的方式在表格中传入url展示图片
求问AntdTable中是否有相应的方法展示图片 试了一下columns中的renderType为link data中target: url的方式好像不行

**Comment by CNFeffery** [comment]
好的，之前我没这方面需求就没开发相关功能，我今天测试一下如果感觉合理下个版本会放出这个新特性

**Comment by wjlyclll** [comment]
非常感谢！期待~

**Comment by CNFeffery** [comment]
@wjlyclll `0.1.8`版本已发布，你描述的已经在`'image'`再渲染模式中实现，欢迎前往官网学习相关参数及示例：
![image](https://user-images.githubusercontent.com/49147660/163708286-047c4b05-13c3-4e48-a3e7-15361a6f5a6d.png)
