### ISSUE TITLE
AntdTreeSelect: Add support for lazy loading tree node

### ISSUE THREAD

**Issue by fishb1** [CNFeffery/feffery-antd-components#222]
Ant Design TreeSelect component has a feature for asynchronous loading of tree nodes. 

![ezgif-5-b06e8aee7f](https://github.com/user-attachments/assets/216cf792-039c-4c9d-8337-6140a108cb13)

You can define a callback function `loadData` for the component and the function is called when a non-leaf tree node is expanded. It is also loading indication displayed until the function returns the result.

![image](https://github.com/user-attachments/assets/8a77bc69-73ea-49ce-9ff9-f00ad50a12e0)

It would be really helpful to have this feature in AntdTreeSelect.

**Comment by CNFeffery** [comment]
@fishb1 Starting from version 0.3.5, fac supports it. Relevant examples:

https://fac.feffery.tech/AntdTreeSelect#demo-container-async_load_node
https://fac.feffery.tech/AntdTree#demo-container-async_load_node
