### ISSUE TITLE
AntdTable超链接模式下可以每行自定义renderLinkText吗？目前好像只能通过renderOptions设定，这样的话所有行的text都是一样的。

### ISSUE THREAD

**Issue by zhanghaitao1** [CNFeffery/feffery-antd-components#24]

**Comment by CNFeffery** [comment]
感谢你的建议，下个版本`0.1.13`我会添加相关功能

**Comment by zhanghaitao1** [comment]
> 感谢你的建议，下个版本`0.1.13`我会添加相关功能

感谢感谢，感觉您这个AntdTable比dash_table强大多了

**Comment by CNFeffery** [comment]
@zhanghaitao1  `0.1.13`版本已发布，你描述的需求现在可以通过`data`参数中定义的数据的`content`键值对来单独设置每个单元格链接的文字内容，从而实现单元格级覆盖`renderLinkText`的设定
