### ISSUE TITLE
Component Token support

### ISSUE THREAD

**Issue by ceeskaan** [CNFeffery/feffery-antd-components#240]
Hi!

With fac.AntdConfigProvider I seem to be able to add global tokens to style the UI components. Is it also already possible to customize specific components tokens like https://ant.design/docs/react/customize-theme?

Thank you in advance! You are doing awesome work!

**Comment by CNFeffery** [comment]
@ceeskaan You can refer to this example: https://py.cafe/CNFeffery/use-ant-design-component-token-in-fac. After I will add style token playground in fac's website based on [py.cafe](https://py.cafe/).

**Comment by CNFeffery** [comment]
By the way, `fac` website in the internationalization of the Chinese/English bilingual construction at present, if you are interested in open source contributions, you can refer to https://github.com/CNFeffery/feffery-antd-docs/issues/166' for contribution guide

**Comment by ceeskaan** [comment]
Perfect. I also just found the componentToken prop in fac.AntdConfigProvider. There you can just define a dict with your components and their corresponding styles, works perfectly.

Many thanks again!
