### ISSUE TITLE
给AntdTable的迷你图tooltips添加描述信息

### ISSUE THREAD

**Issue by vnnw** [CNFeffery/feffery-antd-components#25]
<img width="308" alt="image" src="https://user-images.githubusercontent.com/4979571/173596260-1f9fbcf9-891a-4931-9a00-90612a2a9583.png">

AntdTable 迷你图tooltips 默认只显示数值，可视化效果不理想。
可否在TinyLine, TinyArea, TinyColumn里，传入类似Ant design官方示例里的信息 https://charts.ant.design/zh/examples/tiny/tiny-column#basic-column 
```
tooltip: {
  customContent: function (x, data) {
    return `NO.${x}: ${data[0]?.data?.y.toFixed(2)}`;
  },
},
```
譬如，传入跟data数组等长的string array，提取对应位置的信息，完善迷你图数值提示信息。

**Comment by CNFeffery** [comment]
@vnnw 因为这个功能的设定是“迷你图”，所以并没有把antd charts里很多复杂功能塞进去 既臃肿还会在单元格狭小的容器里引发一些显示问题，但你说的这个tooltip自定义格式还是比较轻量，我会在下个版本添加相关功能

**Comment by CNFeffery** [comment]
@vnnw  `0.1.14`版本开始已添加相关功能，详情参考：
![image](https://user-images.githubusercontent.com/49147660/176609539-4e115227-3e85-4e05-8765-be4dc7f91283.png)
