### ISSUE TITLE
AntdTable再渲染模式下mini图控制绘制颜色

### ISSUE THREAD

**Issue by GerrardYNWA** [CNFeffery/feffery-antd-components#252]
单元格内容再渲染类型renderType为

- mini-line
- mini-bar
- mini-area

时，能否增加可选配置color用于控制绘制线条的颜色？

```python
'renderOptions': {
    'renderType': 'mini-line', 
    'tooltipCustomContent': """(x, data) => `涨跌幅：${data[0]?.data?.y.toFixed(2)}`""",
    # 'lineColor': '#114514',
}
```

**Comment by CNFeffery** [comment]
fac`0.3.8`版本开始已支持，具体见官网示例：

https://fac.feffery.tech/AntdTable-rerender#demo-container-mini_line_mode
https://fac.feffery.tech/AntdTable-rerender#demo-container-mini_bar_mode
https://fac.feffery.tech/AntdTable-rerender#demo-container-mini_area_mode
