### ISSUE TITLE
0.1.13版本卡片网格都竖排了

### ISSUE THREAD

**Issue by sylvoslee** [CNFeffery/feffery-antd-components#26]
![image](https://user-images.githubusercontent.com/34852097/175890766-e38e75ce-66db-43a3-b29e-cd909e61a2e2.png)

**Comment by CNFeffery** [comment]
这个最新开发版在几天前已经修复了，下个版本会正式修复

**Comment by CNFeffery** [comment]
`0.1.14`版本中已修复
