### ISSUE TITLE
如何实现自定义图标

### ISSUE THREAD

**Issue by yangjh-xbmu** [CNFeffery/feffery-antd-components#28]
antd 的图标组件可以自定义图标，fac中的图标组件是否支持自定义图标呢？

**Comment by CNFeffery** [comment]
`AntdIcon`的意义就是引入一系列预设的我精选的图标，这些图标并不是仅仅来自`antd`，你如果需要自定义图标，那建议配合fontawesome的静态文件，通过css类来配合`dash.html`使用各种图标
