### ISSUE TITLE
table单元格可以做下拉菜单吗

### ISSUE THREAD

**Issue by sylvoslee** [CNFeffery/feffery-antd-components#3]
如题

**Comment by CNFeffery** [comment]
@sylvoslee 你说的这类  都是我目前认为多余的功能，没必要嵌入表格中，我目前对`AtndTable`的定位是展示探索数据，并且可以进行内容编辑和更新就可以了

**Comment by sylvoslee** [comment]
这个功能还会考虑吗

**Comment by CNFeffery** [comment]
@sylvoslee 不知道你具体指哪种菜单  是只需要排布若干带链接的菜单项，还是需要监听点击事件
