### ISSUE TITLE
[Feature Request]添加美观的可关闭卡片组件

### ISSUE THREAD

**Issue by CNFeffery** [CNFeffery/feffery-antd-components#32]

**Comment by CNFeffery** [comment]
可针对`Modal`设置`closeIcon`参数自由定义关闭按钮：

```jsx
closeIcon={
  <CloseCircleTwoTone
    style={{
      fontSize: 30,
      position: "absolute",
      top: -15,
      right: -15
    }}
  />
}
```

**Comment by CNFeffery** [comment]
@Coding-with-Adam 
Thank you for your affirmation, `dash` is a wonderful tool to build web app, I'm glad to create more expand functionality for it🤗.

**Comment by Coding-with-Adam** [comment]
Thank you. We look forward to it. 
Do you know https://github.com/roeap/dash-ant-design-components

**Comment by CNFeffery** [comment]
@Coding-with-Adam 
Never heard of it before, I went to have a look, it contains some common components which already exists in my library, what I do in `feffery-antd-components` is not only porting components from Ant Design and Ant Design Pro, but also create new components to implement special functions.

**Comment by CNFeffery** [comment]
@Coding-with-Adam 
You can contact me at my email address: `fefferypzy@gmail.com`

**Comment by CNFeffery** [comment]
最新开发版本中已添加`AntdPopupCard`组件 ✅
