### ISSUE TITLE
请问upload 功能是否支持设置默认多文件路径，只需要用户click一下按钮就可以上传

### ISSUE THREAD

**Issue by guowei0419** [CNFeffery/feffery-antd-components#33]
需求原因是 需要读取的data存在网盘上，但是server没有权限访问网盘，用户有网盘访问权限，是不是实现上只能走 upload的方式了，如果这样的话，尽量对用户友好，考虑通过默认写上多文件网盘路径，用户最终确认上传就可以读取数据，请问有更好建议，或者当前upload功能是否能实现？

**Comment by CNFeffery** [comment]
如果你的网盘文件是可以通过接口方式读取的话，那就不需要通过上传组件，可以直接从服务端调用接口把文件下载到服务器，你在`dash`应用中让用户可以启动服务端对应下载逻辑就行

**Comment by guowei0419** [comment]
> 如果你的网盘文件是可以通过接口方式读取的话，那就不需要通过上传组件，可以直接从服务端调用接口把文件下载到服务器，你在`dash`应用中让用户可以启动服务端对应下载逻辑就行

 研究了一下，权限比较难搞，如果让user上传的话，请问可以设置默认路径吗，这样写死，只要user有网盘权限点下upload就可以

**Comment by CNFeffery** [comment]
@guowei0419 可是`fac`中几个上传组件都是基于用户本地文件系统，调用`flask`实现文件上传的，你说的网盘`dash`应用这边怎么访问得到

**Comment by guowei0419** [comment]
> @guowei0419 可是`fac`中几个上传组件都是基于用户本地文件系统，调用`flask`实现文件上传的，你说的网盘`dash`应用这边怎么访问得到

对于用户来说，只要他有权限，打开网盘和打开本地文件家一样，只是路径不同，我实验用户可以通过upload 功能上传文件，只是不清楚当前upload功能 能否hardcode或者设置默认上传文件路径

**Comment by CNFeffery** [comment]
@guowei0419 我查了一下相关的问题，应该是不太可能实现的（https://stackoverflow.com/questions/59848924/react-js-ant-design-upload-default-directory），每次点击打开的路径都是上一次完成上传任务的路径

**Comment by guowei0419** [comment]
> @guowei0419 我查了一下相关的问题，应该是不太可能实现的（ https://stackoverflow.com/questions/59848924/react-js-ant-design-upload-default-directory ），每次点击打开的路径都是上一次完成上传任务的路径

多谢！
