### ISSUE TITLE
Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by guowei0419** [CNFeffery/feffery-antd-components#35]
使用了table的功能，根据过滤条件会显示过滤后的数据，会随机的报以下 ERROR， 像是哪里timeout了
![image](https://user-images.githubusercontent.com/8343045/184907222-a5660bab-3554-4184-8adb-73ed33342429.png)
🛑 Errors (1)
×
⛑️
Cannot read properties of null (reading 'toString')
8:58:25 PM
Cannot read properties of null (reading 'toString')
(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
TypeError: Cannot read properties of null (reading 'toString')

    at http://127.0.0.1:8050/_dash-component-suites/feffery_antd_components/feffery_antd_components.v0_2_0m1660295865.min.js:1:1609391

    at Array.map (<anonymous>)

    at _loop (http://127.0.0.1:8050/_dash-component-suites/feffery_antd_components/feffery_antd_components.v0_2_0m1660295865.min.js:1:1609361)

    at AntdTable.render (http://127.0.0.1:8050/_dash-component-suites/feffery_antd_components/feffery_antd_components.v0_2_0m1660295865.min.js:1:1609694)

    at finishClassComponent (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_0m1658306675.14.0.js:17295:33)

    at updateClassComponent (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_0m1658306675.14.0.js:17245:26)

    at beginWork (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_0m1658306675.14.0.js:18755:18)

    at HTMLUnknownElement.callCallback (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_0m1658306675.14.0.js:182:16)

    at Object.invokeGuardedCallbackDev (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_0m1658306675.14.0.js:231:18)

    at invokeGuardedCallback (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_0m1658306675.14.0.js:286:33)

**Comment by CNFeffery** [comment]
@guowei0419 收到，可以提供复现错误的示例数据+代码吗

**Comment by guowei0419** [comment]
@CNFeffery  数据是公司内部数据，不便提供，不过如果需要测试，请告诉怎么配合，我可以帮忙验证

**Comment by CNFeffery** [comment]
@guowei0419 你只附上涉及`AntdTable`的代码也可以，顺带描述一下表格中数据各字段的类型

**Comment by guowei0419** [comment]
@CNFeffery  以下是出ERROR的table，我是参考 DASH公众号上的“股市分析” 做的一个页面，先是从表格中选一行，然后针对选中行，从其他数据中filter出来想要的信息，通过新的table显示在页面。
            html.Div(
                [
                    html.H2(
                        'Test case status',
                        style={
                            'borderLeft': '4px solid grey',
                            'padding': '3px 0 3px 10px',
                            'backgroundColor': '#f5f5f5'
                        }
                    ),
                    fac.AntdTable(
                        id='single-feature_case-info-table',
                        locale='en-us',
                        columns=[
                            {
                                'title': 'MR#-SP#',
                                'dataIndex': 'MR#-SP#',
                                'width': 100,
                                'fixed': 'left'
                            },
                            {
                                'title': 'SP name',
                                'dataIndex': 'SP name',
                                'width': 270,
                                'fixed': 'left'
                            },
                            {
                                'title': 'TC#',
                                'dataIndex': 'TC#',
                                'width': 70,
                                'align': 'left'
                            },
                            {
                                'title': 'TC Tag',
                                'dataIndex': 'TC Tag',
                                'width': 400,
                                'align': 'left'
                            },
                            {
                                'title': 'Vendor',
                                'dataIndex': 'Vendor',
                                'width': 80,
                                'align': 'left'
                            },
                            {
                                'title': 'Status',
                                'dataIndex': 'Status',
                                'width': 120,
                                'align': 'left'
                            },
                            {
                                'title': 'Date',
                                'dataIndex': 'Date',
                                'width': 100,
                                'align': 'left'
                            },
                            {
                                'title': 'Year-Week',
                                'dataIndex': 'Year-Week',
                                'width': 100,
                                'align': 'left'
                            },
                            {
                                'title': 'Tester',
                                'dataIndex': 'Tester',
                                'width': 110,
                                'align': 'left'
                            },
                            {
                                'title': 'Comment',
                                'dataIndex': 'Comment',
                                'width': 700,
                                'align': 'left'
                            },
                        ],
                        sortOptions={
                            'sortDataIndexes': ['Date', 'Year-Week'],
                            'multiple': True
                        },
                        filterOptions={
                            'Vendor': {},
                            'Status': {},
                            'MR#-SP#': {
                                'filterMode': 'keyword'
                            },
                            'SP name': {
                                'filterMode': 'keyword'
                            },
                            'TC#': {
                                'filterMode': 'keyword'
                            },
                            'TC Tag': {
                                'filterMode': 'keyword'
                            },
                            'Comment': {
                                'filterMode': 'keyword'
                            },
                            'Tester': {
                                'filterMode': 'keyword'
                            },
                        },
                        maxWidth=2100,
                        maxHeight=700,
                        data=selected_single_feature_case_info.to_dict('records'),
                        bordered=True,
                        pagination={
                            'pageSize': 20,
                            'showSizeChanger': False,
                            'showQuickJumper': True,
                            'showTotalPrefix': 'A total of ',
                            'showTotalSuffix': ' features'
                        }
                    ),
                ]
            ),

selected_single_feature_case_info.dtypes :
Feature name#            object
Feature ID            object
Test Case Group    object
TC#                object
TC Tag             object
Status             object
Date               object
Tester             object
Comment            object
Year-Week          object
Year                 object
Vendor             object
dtype: object

**Comment by CNFeffery** [comment]
@guowei0419 卸载先前版本后，试试最新的仓库开发版本中，你遇到的问题有没有得到解决

**Comment by guowei0419** [comment]
@CNFeffery  issue已修复，
![0217C950](https://user-images.githubusercontent.com/8343045/185450550-8732abad-7b67-494d-b1ea-61e69df3fc18.png)
