### ISSUE TITLE
Cannot read properties of null (reading 'toLowerCase')

### ISSUE THREAD

**Issue by guowei0419** [CNFeffery/feffery-antd-components#36]
使用table的select功能，每次选定一行，然后对数据加工，通过另一个表格显示出加工后的数据，随机报以下错误。

![image](https://user-images.githubusercontent.com/8343045/186087296-a35fea6e-c322-44d7-ab04-dab70391052e.png)
(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
TypeError: Cannot read properties of null (reading 'toLowerCase')

    at Object.eval [as onCell] (eval at render (http://127.0.0.1:8050/_dash-component-suites/feffery_antd_components/feffery_antd_components.v0_2_0m1661232582.min.js:1:1601493), <anonymous>:5:63)

    at http://127.0.0.1:8050/_dash-component-suites/feffery_antd_components/feffery_antd_components.v0_2_0m1661232582.min.js:1:922928

    at Array.map (<anonymous>)

    at p (http://127.0.0.1:8050/_dash-component-suites/feffery_antd_components/feffery_antd_components.v0_2_0m1661232582.min.js:1:922584)

    at renderWithHooks (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_1m1661224876.14.0.js:14938:20)

    at updateFunctionComponent (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_1m1661224876.14.0.js:17169:22)

    at beginWork (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_1m1661224876.14.0.js:18745:18)

    at HTMLUnknownElement.callCallback (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_1m1661224876.14.0.js:182:16)

    at Object.invokeGuardedCallbackDev (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_1m1661224876.14.0.js:231:18)

    at invokeGuardedCallback (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_1m1661224876.14.0.js:286:33)

**Comment by CNFeffery** [comment]
我感觉跟你上次问的那个类似，你是不是数据里有缺失值，我晚上回家了定位一下

**Comment by guowei0419** [comment]
df.fillna('', inplace=True) ，  建议我这边这么操作下吗，或者有什么好的方式，从input这边做些优化

**Comment by CNFeffery** [comment]
@guowei0419 把你以前版本`fac`卸载掉，试试仓库最新开发版正常了没

**Comment by guowei0419** [comment]
应该是还会出现，下边是打印，data做了处理后df.fillna('', inplace=True)， 没问题了

(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
TypeError: Cannot read properties of null (reading 'toLowerCase')

    at Object.eval [as onCell] (eval at render (http://127.0.0.1:8050/_dash-component-suites/feffery_antd_components/feffery_antd_components.v0_2_0m1661264760.min.js:1:1601498), <anonymous>:5:63)

    at http://127.0.0.1:8050/_dash-component-suites/feffery_antd_components/feffery_antd_components.v0_2_0m1661264760.min.js:1:922928

    at Array.map (<anonymous>)

    at p (http://127.0.0.1:8050/_dash-component-suites/feffery_antd_components/feffery_antd_components.v0_2_0m1661264760.min.js:1:922584)

    at renderWithHooks (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_1m1661224876.14.0.js:14938:20)

    at updateFunctionComponent (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_1m1661224876.14.0.js:17169:22)

    at beginWork (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_1m1661224876.14.0.js:18745:18)

    at HTMLUnknownElement.callCallback (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_1m1661224876.14.0.js:182:16)

    at Object.invokeGuardedCallbackDev (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_1m1661224876.14.0.js:231:18)

    at invokeGuardedCallback (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_6_1m1661224876.14.0.js:286:33)

**Comment by guowei0419** [comment]
下边是报错的table           
         fac.AntdTable(
                        id='single-feature_case-info-table',
                        locale='en-us',
                        columns=[
                            {
                                'title': 'feature id',
                                'dataIndex': 'feature id',
                                'width': 100,
                                'fixed': 'left'
                            },
                            {
                                'title': 'feature name',
                                'dataIndex': 'feature name',
                                'width': 270,
                                'fixed': 'left'
                            },
                            {
                                'title': 'TC#',
                                'dataIndex': 'TC#',
                                'width': 70,
                                'align': 'left'
                            },
                            {
                                'title': 'TC Tag',
                                'dataIndex': 'TC Tag',
                                'width': 400,
                                'align': 'left'
                            },
                            {
                                'title': 'Vendor',
                                'dataIndex': 'Vendor',
                                'width': 80,
                                'align': 'left'
                            },
                            {
                                'title': 'Status',
                                'dataIndex': 'Status',
                                'width': 120,
                                'align': 'left'
                            },
                            {
                                'title': 'Date',
                                'dataIndex': 'Date',
                                'width': 100,
                                'align': 'left'
                            },
                            {
                                'title': 'Year-Week',
                                'dataIndex': 'Year-Week',
                                'width': 100,
                                'align': 'left'
                            },
                            {
                                'title': 'Tester',
                                'dataIndex': 'Tester',
                                'width': 110,
                                'align': 'left'
                            },
                            {
                                'title': 'Comment',
                                'dataIndex': 'Comment',
                                'width': 700,
                                'align': 'left'
                            },
                        ],
                        sortOptions={
                            'sortDataIndexes': ['Date', 'Year-Week'],
                            'multiple': True
                        },
                        filterOptions={
                            'Vendor': {},
                            'Status': {},
                            'MR#-SP#': {
                                'filterMode': 'keyword'
                            },
                            'SP name': {
                                'filterMode': 'keyword'
                            },
                            'TC#': {
                                'filterMode': 'keyword'
                            },
                            'TC Tag': {
                                'filterMode': 'keyword'
                            },
                            'Comment': {
                                'filterMode': 'keyword'
                            },
                            'Tester': {
                                'filterMode': 'keyword'
                            },
                        },
                        conditionalStyleFuncs={
                            'Status': '''
                                (record, index) => {
                                    let ulmStrings = ['abc']
                                    let notstartStrings = ['not start', 'nan']
                                    status = record['Status'].toLowerCase()
                                    if ( ulmStrings.map(s => status.includes(s)).some(x => x)) {
                                        return {style: {backgroundColor: "#92D050", color: "white"}};
                                    } else if ( status === 'passed' ) {
                                        return {style: {backgroundColor: "#00B050", color: "white"}};
                                    } else if ( status.includes('deviation')) {
                                        return {style: {backgroundColor: "#5AD8A6", color: "white"}};
                                    } else if ( status.includes('fail')) { 
                                        return {style: {backgroundColor: "#E8684A", color: "white"}};
                                    } else if ( status.includes('ongoing')) {
                                        return {style: {backgroundColor: "#F6BD16", color: "white"}};
                                    } else if ( status.includes('not applicable')) {
                                        return {style: {backgroundColor: "#5D7092", color: "white"}};
                                    } else if ( notstartStrings.map(s => status.includes(s)).some(x => x)) {
                                        return {style: {backgroundColor: "#929292", color: "white"}};
                                    } else if ( status.includes('skip') ) {
                                        return {style: {backgroundColor: "#9270CA", color: "white"}};
                                    }
                                }
                            '''
                        },
                        maxWidth=2100,
                        maxHeight=700,
                        data=selected_single_feature_case_info.to_dict('records'),
                        bordered=True,
                        pagination={
                            'pageSize': 20,
                            'showSizeChanger': False,
                            'showQuickJumper': True,
                            'showTotalPrefix': 'A total of ',
                            'showTotalSuffix': ' cases'
                        }
                    ),

**Comment by guowei0419** [comment]
selected_single_feature_case_info.dtypes :
Feature name# object
Feature ID object
Test Case Group object
TC# object
TC Tag object
Status object
Date object
Tester object
Comment object
Year-Week object
Year object
Vendor object
dtype: object

**Comment by CNFeffery** [comment]
@guowei0419 可以去试试最新仓库开发版本，我这边一直复现不出来，只能估计着可能导致这个问题的位置进行修复了
