### ISSUE TITLE
English Documentation

### ISSUE THREAD

**Issue by Willem770** [CNFeffery/feffery-antd-components#44]
CNFeffery I saw somewhere you wanted to add English documentation and wanted help. I myself use Dash a bit, and just started learning React, I have a website with a friend built in python dash and he did most of the code in python dash, however, I was searching for antd in python dash. Since I like antd buttons and components with respect to look more than the bootstrap components. I myself don't know the language it is in now.

**Comment by CNFeffery** [comment]
@Willem770 Current language in my document website is Chinese, In the short term you can use Google Translate to learn how to use, I will deploy English document website when I complete the `0.2.0` stable version.

**Comment by diogommartins** [comment]
> @Willem770 Current language in my document website is Chinese, In the short term you can use Google Translate to learn how to use, I will deploy English document website when I complete the `0.2.0` stable version.

If you need any help from a non Chinese speaker, I'm also interested in English documentation and would gladly help.

**Comment by georgiossalon** [comment]
Having documentation in English would be amazing.

**Comment by CNFeffery** [comment]
@georgiossalon The parameter explanations for the sidebar components on the official website can now be switched to English, based on the translation by ChatGPT🤣.

**Comment by georgiossalon** [comment]
@CNFeffery Nice. This is a step forward :)

**Comment by CNFeffery** [comment]
The official website of `fac` has recently completed a major restructuring and upgrade for the new `0.3.x` version, and has recently added international multi-language features. Interested friends can learn about the technical details of contributing component English documentation pages to the `fac` official website through https://github.com/CNFeffery/feffery-antd-docs/issues/166.

![image](https://github.com/user-attachments/assets/7173c08f-94ff-410f-a558-4c4484905794)

**Comment by CNFeffery** [comment]
Discuss the related content, please transfer to https://github.com/CNFeffery/feffery-antd-docs/issues/166

**Comment by CNFeffery** [comment]
@michaelrussell4 You can refer to https://github.com/CNFeffery/feffery-antd-docs/issues/169 website in fac document international contribution.😊
