### ISSUE TITLE
Typo in AntdTable

### ISSUE THREAD

**Issue by zeitderforschung** [CNFeffery/feffery-antd-components#47]
https://github.com/CNFeffery/feffery-antd-components/blob/2be36153008f788b4cbb01c9647d8d70ec0ccbec/src/lib/components/AntdTable.react.js#L911

Should be `recentlySwitchRow` and `recentlySwitchStatus `.

**Comment by CNFeffery** [comment]
😂these spelling mistakes fixed in `0.2.0rc18`
