### ISSUE TITLE
AntdTreeSelect - support showCheckedStrategy

### ISSUE THREAD

**Issue by swt2c** [CNFeffery/feffery-antd-components#52]
Hi, would it be possible to add support for `showCheckedStrategy` parameter for `AntdTreeSelect`?

Thanks!

**Comment by CNFeffery** [comment]
@swt2c Available in [0.2.0rc23](https://pypi.org/project/feffery-antd-components/0.2.0rc23/)
![image](https://user-images.githubusercontent.com/49147660/216752765-6041860b-6c35-4560-b020-f330746de01d.png)

**Comment by swt2c** [comment]
Thank you!
