### ISSUE TITLE
fac.AntdDatePicker独占一行

### ISSUE THREAD

**Issue by xiongyifan** [CNFeffery/feffery-antd-components#53]
当把fac.AntdDatePicker放在dbc.Container或者dbc.Col中时会独占一行

![捕获](https://user-images.githubusercontent.com/8685012/216852854-0c2343bf-bed4-4a9e-a845-9620dd0fd8cf.PNG)

代码如下：
```python
import dash
import dash_bootstrap_components as dbc
import feffery_antd_components as fac

app = dash.get_app()

dash.register_page(__name__, path='/')

layout = dbc.Container(
    [
        fac.AntdSwitch(),
        fac.AntdDatePicker(),
    ],
)
```

请问，可以让fac.AntdDatePicker和fac.AntdSwitch在一行显示吗

**Comment by CNFeffery** [comment]
@xiongyifan 首先我建议你不要在同一个项目里同时使用`dbc`与`fac`，会存在部分样式冲突，其次你可以使用`fac.AntdSpace`的横向模式或`fac.AntdRow`套`fac.AntdCol`的方式完成你的需求，具体见我的官网

**Comment by CNFeffery** [comment]
譬如：

![image](https://user-images.githubusercontent.com/49147660/216918638-febaa9c3-e559-401b-903a-ee7ff54af397.png)
![image](https://user-images.githubusercontent.com/49147660/216918671-8e60768a-e41b-49a3-814a-a8040d1b53eb.png)

**Comment by xiongyifan** [comment]
666，fac.AntdSpace可以。

https://dash-bootstrap-components.opensource.faculty.ai/docs/components/navbar/
主要dbc的导航可以直接用

https://fac.feffery.tech/AntdLayout
fac我也试了，但是前端基础太差，搞不定。。。

**Comment by CNFeffery** [comment]
@xiongyifan 你这个完全可以用`fac.AntdTabs`来实现同样的标签页效果

**Comment by CNFeffery** [comment]
@xiongyifan 没事 你如果觉得改以前的`dbc`代码麻烦可以先混着用，遇到具体问题再说

**Comment by CNFeffery** [comment]
@xiongyifan 你可以仔细看看我的官网，`fac.AntdMenu`有3种显示模式，有水平模式

**Comment by CNFeffery** [comment]
你可以看我官网的说明加我vx好友，我有个dash交流群，你平时有小问题可以在群里问

**Comment by xiongyifan** [comment]
好啊，已加微信。确实，一看都是左侧导航，就没仔细看。

https://github.com/ned2/slapdash

有没有计划搞个脚手架，项目建起来，导航有了，剩下的难度就低了，新手友好。

**Comment by xiongyifan** [comment]
好啊，已加微信。确实，一看都是左侧导航，就没仔细看。

https://github.com/ned2/slapdash

有没有计划搞个脚手架，项目建起来，导航有了，剩下的难度就低了，新手友好。

**Comment by CNFeffery** [comment]
@xiongyifan 目前业余时间都在忙着开发`fac` 0.2.0新版本的官网，后面可以研究一下脚手架相关功能

**Comment by xiongyifan** [comment]
非常期待后续的新功能
