### ISSUE TITLE
dash原生的 Dropdown 可以基于输入的内容触发callback，从而来实时返回options，不知AntdSelect是否能做出类似地效果呢？

### ISSUE THREAD

**Issue by zhanghaitao1** [CNFeffery/feffery-antd-components#55]

**Comment by CNFeffery** [comment]
@zhanghaitao1 请参考：http://fac-next.feffery.tech/AntdSelect#%E9%85%8D%E5%90%88autoSpin%E5%AE%9E%E7%8E%B0%E8%BF%9C%E7%A8%8B%E9%80%89%E9%A1%B9%E5%8A%A0%E8%BD%BD

**Comment by zhanghaitao1** [comment]
试了非常好用，谢谢~
