### ISSUE TITLE
Invalid argument `prefix` passed into AntdStatistic

### ISSUE THREAD

**Issue by zeitderforschung** [CNFeffery/feffery-antd-components#57]
The following code fails with the latest feffery-antd-components==0.2.0rc31 build. This is a simple example, but in a more complex example other things fail too, so maybe it is not related to AntdStatistic directly.

**Example**

```python
from dash import Dash
import feffery_antd_components as fac

app = Dash()
server = app.server

def create_layout():
    return fac.AntdStatistic(
        value=1000,
        prefix={
            'mode': 'icon',
            'content': 'antd-file-done'
        },
    )

app.layout = create_layout

if __name__ == '__main__':
    app.run(host='0.0.0.0', port='80', debug=True)
```

**Error**

```
Invalid argument `prefix` passed into AntdStatistic.
Expected a ReactNode.
Value provided: 
{
  "mode": "icon",
  "content": "antd-file-done"
}
```

**Comment by zeitderforschung** [comment]
@CNFeffery Oh thank you, seems I checked the wrong documentation.

**Comment by zeitderforschung** [comment]
@CNFeffery I stumbled across another change, you changed `is_open` to `isOpen`, I guess you are now using camelCasing instead of snake_casing to be closer to the Ant Design API. Is there a migration guide for the major issues from 0.1 to 0.2?

**Comment by CNFeffery** [comment]
@zeitderforschung Of course, I will add change log and migration guide as I finished all document pages of components😃.
