### ISSUE TITLE
AntdTree 增加collapse参数

### ISSUE THREAD

**Issue by zhanghaitao1** [CNFeffery/feffery-antd-components#58]
不知AntdTree是否可能增加collapse参数，这样就可以通过callback控制tree的展开和折叠。

**Comment by CNFeffery** [comment]
@zhanghaitao1 你控制参数`expandedKeys`不能满足需求吗，一棵树层次比较复杂，不知道你需要的展开具体是什么样的

**Comment by zhanghaitao1** [comment]
试了一下，好像不行。因为我的树比较大，我是想通过一个按钮来控制整个树的展开或折叠，例如下面这个按钮点击一下能折叠整个树，再点击一下能展开整个树。
![image](https://user-images.githubusercontent.com/37844800/226108971-90d852d4-86c1-4fbd-93d9-130061f08e8f.png)

**Comment by CNFeffery** [comment]
@zhanghaitao1 这个直接在`AntdTree`的内部确实不太好实现，我的建议是你可以用`jsonpath`之类的工具在应用初始化时计算得到你的树中所有可展开的节点的key值数组，作为`Store`存放在页面中，然后每次点击展开按钮时实际是对`AntdTree`的`expandedKeys`进行这个数组的输出即可，收起就是输出`[]`

**Comment by zhanghaitao1** [comment]
> @zhanghaitao1 这个直接在`AntdTree`的内部确实不太好实现，我的建议是你可以用`jsonpath`之类的工具在应用初始化时计算得到你的树中所有可展开的节点的key值数组，作为`Store`存放在页面中，然后每次点击展开按钮时实际是对`AntdTree`的`expandedKeys`进行这个数组的输出即可，收起就是输出`[]`

感谢建议，试了一下，方法确实可行
