### ISSUE TITLE
Support for Pattern-Matching (Dynamic Components)

### ISSUE THREAD

**Issue by DarkCTO** [CNFeffery/feffery-antd-components#64]
[Dash v1.11.0 Release - Introducing Pattern-Matching Callbacks](https://community.plotly.com/t/dash-v1-11-0-release-introducing-pattern-matching-callbacks/37592/2)

Can I do the same thing here but for antd components?
id for fac is a string, while dcc proves an index.

Two ways I'm thinking of:

id='input-' + nClicks

Use className property (I do not know how to use this in Dash, only for JS styling)

**Comment by CNFeffery** [comment]
Pattern-Matching Callbacks is basic capabilities of dash, fac as a standard component library certainly supports these features.

**Comment by CNFeffery** [comment]
For example, I will adjust the type description of the id parameter in the document, which was not fully written before:
![image](https://user-images.githubusercontent.com/49147660/233755014-23978417-2af8-4f69-9d26-97b356c7f035.png)

**Comment by DarkCTO** [comment]
Thank you. Somehow when I translated to English it showed me id accepts only string.
Solved.

**Comment by DarkCTO** [comment]
@CNFeffery could you also support pattern-matching for containerId of AntdDrawer?
