### ISSUE TITLE
关于页头固定之后，会被表格和图表阻挡的问题

### ISSUE THREAD

**Issue by yinssl** [CNFeffery/feffery-antd-components#65]
页头fixed了之后，会被表格和图表阻挡（其他就不会），如下图。

![捕获](https://user-images.githubusercontent.com/48947900/233824715-085bfea7-a355-4e29-b142-2c467b559a9b.PNG)
![捕获1](https://user-images.githubusercontent.com/48947900/233824716-0e7b5b31-5845-4a43-b659-f36fb8668582.PNG)

**Comment by CNFeffery** [comment]
@yinssl 你可以提供一小段复现这个问题的代码吗

**Comment by yinssl** [comment]
header = [
    fac.AntdHeader(
        [
            fac.AntdTitle(
                'XX-数据分析监控系统',
                level=2,
                style={
                    'color': 'white',
                    'margin': '0'
                },
            ),
        ],
        style={
            'display': 'flex',
            'justifyContent': 'center',
            'alignItems': 'center',
            'backgroundColor': '#169bc0',
            'width': '100%',
            'position': 'fixed',
            'top': 0,
        },
    ),
]

table = [
    fac.AntdTable(
        id='table_flow_v',
        columns=[],
        data=[],
        bordered=True,
        pagination={
            'pageSize': 5,
            'showSizeChanger': True,
            'pageSizeOptions': [5, 10, 20]
        }
    )
]


content = [
    fac.AntdLayout(
        [
            fac.AntdContent(
                table,
                style={
                    'backgroundColor': 'white'
                }
            ),
        ],
        style={
            'height': '1800px'
        }
    ),
]

app.layout = html.Div(
        [
            fac.AntdLayout(
                # 标题
                header,
            ),
            fac.AntdLayout(
                #  内容
                content,
            ),
            fac.AntdLayout(
                #  页脚
                footer,
            ),
            fac.AntdLayout(
                #  缓存
                store,
            )
        ],
        style={
            'height': 'auto',
            'border': '1px solid rgb(241, 241, 241)'
        }
    )

app = DjangoDash('SimpleExample', external_stylesheets=[dbc.themes.BOOTSTRAP])

**Comment by yinssl** [comment]
我是用djangoplotlydash的。

**Comment by CNFeffery** [comment]
@yinssl 你这纯`css`问题，给你那个`fixed`的页首设置`z-index`大一些即可

**Comment by yinssl** [comment]
衷心感谢指导。
