### ISSUE TITLE
Tree data in Antd.Table

### ISSUE THREAD

**Issue by ceeskaan** [CNFeffery/feffery-antd-components#66]
Hi, awesome components!

In a previous version (0.1.16), I was able to pass "children" keys into the data in Antd.Table. This way the table automatically nests the rows based on this key. In newer version this does not seem to work anymore. 

Is there any way you can add this back? Or implement tree data in some other way?

Thank you in advance!

**Comment by CNFeffery** [comment]
@ceeskaan Could you please offer some demo code😀.

**Comment by CNFeffery** [comment]
It will continue to work from next version.
![image](https://user-images.githubusercontent.com/49147660/234845793-8739b963-42ad-47ac-87a1-b0b3e081903a.png)
