### ISSUE TITLE
AntdTree可以增加搜索模式，搜索当前节点，可以增加双击修改和右击菜单   新增和删除功能  antdesign好像有这个功能吧

### ISSUE THREAD

**Issue by UpDownLeftRig** [CNFeffery/feffery-antd-components#67]

**Comment by CNFeffery** [comment]
可搜索功能集成到树里多余了，自己写回调函数配合`AntdInput`来实现就行。

**Comment by CNFeffery** [comment]
双击修改跟右击菜单相关功能你可以提供以下原生`antd`的相关实现示例链接，我看看如果合理可以新增。

**Comment by UpDownLeftRig** [comment]
@CNFeffery 记错了，easy ui 可以编辑。https://www.jeasyui.net/demo_react/929.html。
我看到蚂蚁集团还有几个数据可视化的看框架AntV https://antv.gitee.io/zh。比plotly好，plotly渲染太慢了。能新加一个AntV的组件，就全了

**Comment by CNFeffery** [comment]
> @CNFeffery 记错了，easy ui 可以编辑。[https://www.jeasyui.net/demo_react/929.html。](https://www.jeasyui.net/demo_react/929.html%E3%80%82) 我看到蚂蚁集团还有几个数据可视化的看框架AntV [https://antv.gitee.io/zh。比plotly好，plotly渲染太慢了。能新加一个AntV的组件，就全了](https://antv.gitee.io/zh%E3%80%82%E6%AF%94plotly%E5%A5%BD%EF%BC%8Cplotly%E6%B8%B2%E6%9F%93%E5%A4%AA%E6%85%A2%E4%BA%86%E3%80%82%E8%83%BD%E6%96%B0%E5%8A%A0%E4%B8%80%E4%B8%AAAntV%E7%9A%84%E7%BB%84%E4%BB%B6%EF%BC%8C%E5%B0%B1%E5%85%A8%E4%BA%86)

可以持续关注（ https://github.com/CNFeffery/feffery-antd-charts ），是我对`antd charts`的二次开发，目前处于测试阶段。
