### ISSUE TITLE
Default expanded row nested tree data

### ISSUE THREAD

**Issue by ceeskaan** [CNFeffery/feffery-antd-components#73]
Hi!

The nested tree data is working great! I'm trying to get the top level to be expanded by default, I was looking at defaultExpandedRowKeys but it does not seem to work with expandable rows made with the "children" keys. Is there any way you can fix this?

Second, the search filter seems to only work for the top level, is there any way we could be able to search through every level?

Thank you in advance, you are doing great work!

**Comment by CNFeffery** [comment]
@ceeskaan `defaultExpandedRowKeys` works for nested data too from latest version of `fac` (0.2.9), due to antd's underlying limitations, nested data does not support filtering for the time being.
