### ISSUE TITLE
addOnBefore and addOnAfter for AntdSelect

### ISSUE THREAD

**Issue by DarkCTO** [CNFeffery/feffery-antd-components#76]
Can addOnBefore and after be added to AntdSelect and AntdSelectTree?

I have some widget as AntdInput but for certain inputs I need AntdSelect which doesn't have addOnBefore to match the aesthetics of AntdInputs, could it be an easy add?

**Comment by CNFeffery** [comment]
@DarkCTO I suggest you use the `AntdCompact` component: https://fac.feffery.tech/AntdCompact

**Comment by DarkCTO** [comment]
![brave_KpNZfnaqY0](https://github.com/CNFeffery/feffery-antd-components/assets/99158109/19368429-0a8d-4525-b684-1ba24815d8d1)
So putting AntdCompact with width of 100%, with children equals AntdText and the input component right?

**Comment by CNFeffery** [comment]
@DarkCTO Try like this:
![image](https://github.com/CNFeffery/feffery-antd-components/assets/49147660/bbb8b914-3f67-4456-aad7-04df3a44202e)

```python
html.Div(
    fac.AntdCompact(
        [
            fac.AntdButton(
                'before',
                style={
                    'background': '#fafafa',
                    'pointer-events': 'none'
                }
            ),
            fac.AntdSelect(
                options=[],
                style={
                    'width': '100%'
                }
            ),
            fac.AntdButton(
                'after',
                style={
                    'background': '#fafafa',
                    'pointer-events': 'none'
                }
            )
        ],
        block=True
    ),
    style={
        'width': 300
    }
)
```

**Comment by DarkCTO** [comment]
Sweet!
