### ISSUE TITLE
AntdSelect mode Multiple value=None gives strange input

### ISSUE THREAD

**Issue by DarkCTO** [CNFeffery/feffery-antd-components#78]
`fac.AntdSelect(mode='multiple', options=self.options, placeholder=var, id = {'module':'g_basic_chart', 'component': 'AntdInput', 'index': 0, 'name': var}, value=None, style={'width':'70%'})`

When value=None, the widget gives a tiny input which should not be there?
Any way to not have this small piece with no text out?

![brave_ITQUToJx9g](https://github.com/CNFeffery/feffery-antd-components/assets/99158109/159274c4-899d-42e8-b5ff-ee32aeba869c)

**Comment by CNFeffery** [comment]
@DarkCTO You can fix it like this for now, will be auto-handled inside `AntdSelect` from the next version (0.2.9):

```python
import dash
from dash import html
import feffery_antd_components as fac

app = dash.Dash(__name__)

demo_value = None

app.layout = html.Div(
	[
		fac.AntdSelect(
			options=[
				{
					'label': f'option{i}',
					'value': f'option{i}',
				}
				for i in range(1, 6)
			],
			value=demo_value or [],
			mode='multiple',
			style={
				'width': 150
			}
		)
	],
	style={
		'padding': 50
	}
)

if __name__ == '__main__':
	app.run(debug=True)
```

**Comment by DarkCTO** [comment]
Thanks.
