### ISSUE TITLE
当AntdTable数据更新时，selectedRows的值不会随着更新

### ISSUE THREAD

**Issue by yiz569** [CNFeffery/feffery-antd-components#80]
当AntdTable数据更新时，selectedRows的值不会随着更新

**Comment by CNFeffery** [comment]
@yiz569 这是因为`selectedRows`触发值更新的时机在于行被选择的时候，不过我会想一想在`data`更新时是否要为`selectedRows`同步变化

**Comment by CNFeffery** [comment]
@yiz569 更新`fac`到0.2.9版本，参考[这个例子](https://fac.feffery.tech/AntdTable-advanced#%E5%90%8C%E6%AD%A5%E5%88%B7%E6%96%B0selectedRows)

**Comment by CNFeffery** [comment]
@yiz569 我官网的示例没问题，不知道你可否提供你的可复现代码

**Comment by CNFeffery** [comment]
@yiz569 注意按照这个示例的额外说明来做，你的`data`参数中各个行的记录字典里需要预先有自定义的`key`值，不能使用`AntdTable`内部缺省自动生成的递增序列`key`：
![image](https://github.com/CNFeffery/feffery-antd-components/assets/49147660/9aae40af-8ebb-44b0-8f85-64386a92b94a)

**Comment by yiz569** [comment]
@CNFeffery 谢谢，手动设置key之后已解决问题。如果能用自动生成的key就更好啦。

**Comment by CNFeffery** [comment]
@yiz569 我的建议还是使用自己构造的`key`，一般这种应用中行记录`key`值相当于是主键，最好是自己处理
