### ISSUE TITLE
Sidebar active issue 

### ISSUE THREAD

**Issue by crystle443925** [CNFeffery/feffery-antd-components#82]
import feffery_antd_components as fac 
from dash import Dash, Input, Output, html, dcc
import dash_bootstrap_components as dbc
import dash
from dash import dcc
from dash import html
from dash import dash_table
import numpy as np
from flask import Flask

# Generate a random dataset with 100 rows and 5 columns
np.random.seed(42)
num_rows = 100
num_columns = 5
dataset = np.random.rand(num_rows, num_columns)

# Create the Dash app
application = Flask(__name__)
external_stylesheets = [dbc.themes.BOOTSTRAP]
app = Dash(
    __name__,
    external_stylesheets=external_stylesheets,
    server=application,
    use_pages=True,
    prevent_initial_callbacks=True
)

# Sidebar layout
def sidebar():
        return(
            fac.AntdLayout(
                [
                fac.AntdSider(
                    [
                        fac.AntdMenu(
                            menuItems=[
                                {
                                    'component': 'Item',
                                    'props': {
                                        'key': 1,
                                        'title': f'antd-home',
                                        'icon': 'antd-home',
                                        'href':'/page1'
                                    }
                                },
                                {
                                    'component': 'Item',
                                    'props': {
                                        'key': 2,
                                        'title': f'图标antd-bar-chart',
                                        'icon': 'antd-bar-chart',
                                        'href':'/page2'
                                    }
                                }
                            ],
                            mode='inline',
                            style={
                                'height': '100%',
                                'overflow': 'hidden auto'
                            }
                        )
                    ],
                    style={
                        'position': 'relative'
                    }
                )
            ],
            style={
                'height': '600px'
            }
        )
)
        
#page 1 are in page folder
dash.register_page(
    __name__,
    path='/page1'

)
page1 = dash_table.DataTable(
        id='datatable',
        columns=[{'name': f'Column {i}', 'id': f'column{i}'} for i in range(num_columns)],
        data=[{f'column{i}': dataset[row, i] for i in range(num_columns)} for row in range(num_rows)],
        style_table={'overflowX': 'auto'},
        style_cell={'textAlign': 'center'},
    )

#import layout function
page_title_name = 'page1'
def layout():
    return(
        html.Div([
            fac.AntdLayout(
               [sidebar(),
                html.Div([
                        fac.AntdTitle(
                            page_title_name,
                            level=2,
                            style={'margin-top':'60px'}
                            ),
                        page1],
                        style={'margin-left': '30px'})
            
               ],
        )
    ]
    )
)
    
    
#page 2 in page folder
dash.register_page(
    __name__,
    path='/page2'

)
page2 = dash_table.DataTable(
        id='datatable',
        columns=[{'name': f'Column {i}', 'id': f'column{i}'} for i in range(num_columns)],
        data=[{f'column{i}': dataset[row, i] for i in range(num_columns)} for row in range(num_rows)],
        style_table={'overflowX': 'auto'},
        style_cell={'textAlign': 'center'},
    )

#import layout function
page_title_name = 'Interco Details'
def layout():
    return(
        html.Div([
            fac.AntdLayout(
               [sidebar(),
                html.Div([
                        fac.AntdTitle(
                            page_title_name,
                            level=2,
                            style={'margin-top':'60px'}
                            ),
                        page2],
                        style={'margin-left': '30px'})
            
               ],
        )
    ]
    )
)

# Define the layout
app.layout = html.Div([
    dcc.Location(
        id='url',
        refresh=False,
    ),
    sidebar,
    dash.page_container
])

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True,port=8052)

Hi Feffery,
The design of my dash page is quite similar to this one, I met lots of issues in sidebar part, so when I click the sidebar, the item is not highlighted as I expect, I have to click twice to highlight, also if I click item under sub menu, the sub menu will collapse automatically. Even after I removed all components from bootstrap and dbc, it is still not working. 

It works fine when I only had one internal link (one item href links to internal page), but if I add more items, then it comes this problem. 

Really appreciated if you have any ideas to solve it. The above code is not working properly, but the basic structure is similar.

**Comment by CNFeffery** [comment]
@crystle443925 我注意到你的代码中使用`dash`中的`pages`机制来驱动侧边菜单选项切换对页面内容更新的逻辑，我平时不使用这种方式实现路由（因为我觉得不灵活），你可以参考我`fac`官网中 https://github.com/CNFeffery/feffery-antd-docs/blob/main/app.py#L411 这里的路由实现逻辑，是使用`dcc.Location()`向应用中注入url监听，从而监听触发右侧主体内容更新的，你也可以在*玩转dash*知识星球的[构建多页面应用](https://t.zsxq.com/0eZ9GSGfV)课程中学习具体的原理
