### ISSUE TITLE
AntdTab + FefferyGrid + LeafletMap: Map only good for latest tab.

### ISSUE THREAD

**Issue by DarkCTO** [CNFeffery/feffery-antd-components#84]
So I have tabs, each contains grid, and grid item can contain either table, graph or map.

So you can see, for latest tab the map remembers location, and refresh automatically.
But if I were to go back to previous tab, the map has grey areas, and upon scrolling it doesn't refresh anymore. Please see demo below:

![Animation](https://github.com/CNFeffery/feffery-antd-components/assets/99158109/222e06fe-ae19-4621-8f01-f2171f8e7971)

**Comment by CNFeffery** [comment]
@DarkCTO for `flc`, set `viewAutoCorrection=True` in `flc.LeafletMap()`

**Comment by DarkCTO** [comment]
Thanks. Could be due to the computer or the network, I bring the project home and they load properly.

**Comment by DarkCTO** [comment]
Thanks. Could be due to the computer or the network, I bring the project home and they load properly.

**Comment by DarkCTO** [comment]
`viewAutoCorrection=True ` works well. Thanks.
