### ISSUE TITLE
Change mask color for AntdDrawer

### ISSUE THREAD

**Issue by DarkCTO** [CNFeffery/feffery-antd-components#89]
Hi, I would like to change the color of the mask of something like white.

In summary, I need to have the mask effect without any shadow.

**Comment by CNFeffery** [comment]
@DarkCTO `maskStyle` will be added from the next version:

![image](https://github.com/CNFeffery/feffery-antd-components/assets/49147660/26a7b70a-5521-438b-a31a-35d4982ae772)
![image](https://github.com/CNFeffery/feffery-antd-components/assets/49147660/c794892b-9911-43c4-aec9-d0a51247c64b)
