### ISSUE TITLE
很好用

### ISSUE THREAD

**Issue by limmyforget** [CNFeffery/feffery-antd-components#9]
非常好用，请问0.0.1rc8稳定版快发布了吧

**Comment by CNFeffery** [comment]
@limmyforget 快了  还剩最后几个组件在做了，做完就准备0.0.1正式版的发布了，欢迎提前关注公众号 玩转dash ，之后会发很多教程

**Comment by CNFeffery** [comment]
@limmyforget `0.0.1rc8`已发布，欢迎去官网浏览新功能
