### ISSUE TITLE
AntdTable增加自定义筛选

### ISSUE THREAD

**Issue by yiz569** [CNFeffery/feffery-antd-components#91]
希望AntdTable可以增加自定义筛选菜单，特别是针对数值型列的筛选。

**Comment by CNFeffery** [comment]
@yiz569 我不认为把过多的非必要功能塞进`AntdTable`是件好事，很多特殊需求完全可以联动外部组件来实现，譬如：https://github.com/CNFeffery/feffery-antd-components/issues/60#issuecomment-1501493586

**Comment by yiz569** [comment]
@CNFeffery 当列数量特别多的时候通过外部组件联动实现的话页面会非常的杂乱，Antd本身提供的自定义筛选菜单非常的好用，希望可以支持。

**Comment by CNFeffery** [comment]
@yiz569 那你可以提供一些具体的“数值筛选”示例吗

**Comment by yiz569** [comment]
@CNFeffery 当列为数值型的时候，点击筛选按钮，用户可以输入 min~max 进行筛选。
