### ISSUE TITLE
Double Click and Rename AntdTabs

### ISSUE THREAD

**Issue by DarkCTO** [CNFeffery/feffery-antd-components#94]
How to implement double click events, and rename the tabs in AntdTabs?

I'm trying to mimic Excel behaviors, is there any existing componets either fac or fuc that can achieve this?

![2023-08-14-175200_2496x1468_scrot](https://github.com/CNFeffery/feffery-antd-components/assets/99158109/1eb86fcb-1412-44b6-a75a-2eb7f14702d6)

**Comment by DarkCTO** [comment]
I see, great solution.
Also if I were to implement drag and drop to change tab order, would an event to detect mouse drag is helpful for FefferyDiv here?

Aug 15, 2023 07:38:38 Feffery ***@***.***>:

**Comment by CNFeffery** [comment]
drag and drop to change tab order is an advanced feature, there is no clear way to implement this now.
