### ISSUE TITLE
Trying to achieve a table in an expanded row of a table

### ISSUE THREAD

**Issue by romakoifman** [CNFeffery/feffery-antd-components#95]
Hi,

Something like shown in here - https://codesandbox.io/s/sgwkxs?file=/demo.tsx:2551-2561

Tried to use expandedRowKeyToContent but no luck. Is it possible to get an example please?

Thank you!

**Comment by CNFeffery** [comment]
@romakoifman a basic demo:

![image](https://github.com/CNFeffery/feffery-antd-components/assets/49147660/33194b83-cb32-4b1c-a5a2-6263e280d36f)

```python
import dash
import json
from dash import html
import feffery_antd_components as fac
from dash.dependencies import Input, Output

app = dash.Dash(__name__)

app.layout = html.Div(
    [
        fac.AntdTable(
            locale='en-us',
            columns=[
                {
                    'title': f'outer-field{i}',
                    'dataIndex': f'outer-field{i}',
                    'width': 400
                }
                for i in range(5)
            ],
            data=[
                {
                    **{
                        f'outer-field{j}': i
                        for j in range(5)
                    },
                    'key': f'row-{i}'
                }
                for i in range(10)
            ],
            bordered=True,
            expandedRowKeyToContent=[
                {
                    'key': f'row-{i}',
                    'content': html.Div(
                        fac.AntdTable(
                            columns=[
                                {
                                    'title': f'inner-field{i}',
                                    'dataIndex': f'inner-field{i}',
                                }
                                for i in range(5)
                            ],
                            data=[
                                {
                                    f'inner-field{i}': 'test'
                                    for i in range(5)
                                }
                            ] * 5,
                            bordered=True
                        ),
                        style={
                            'padding': 5
                        }
                    )
                }
                for i in range(0, 10, 2)
            ]
        )
    ],
    style={
        'padding': 50
    }
)


if __name__ == '__main__':
    app.run(debug=True)

```

**Comment by romakoifman** [comment]
Thank you!!

**Comment by romakoifman** [comment]
I see my problem now. I have a mix of rows which are expandable by "children" elements and also trying to add a table by expandedRowKeyToContent not on the top level but deeper on a child row in the tree. Once I add expandedRowKeyToContent children on the top level are not shown at all. 

Is it possible to support a "mix" when expandedRowKeyToContent present and the row id is present in it only then it is applied, otherwise the regular "children" are shown if present

Thank you

**Comment by CNFeffery** [comment]
@romakoifman could you please offer some demo code to reproduce your issue clearly.

**Comment by romakoifman** [comment]
<img width="1463" alt="image" src="https://github.com/CNFeffery/feffery-antd-components/assets/7470461/cebb31ca-ea41-44da-a2ca-b590b62a8c5e">

I would expect that if you uncomment the expandedRowKeyToContent in the code below it would add an expanded row to the first child row keeping all other "children" as the are.

Thank you!

`import dash
import json
from dash import html
import feffery_antd_components as fac
from dash.dependencies import Input, Output

app = dash.Dash(__name__)

app.layout = html.Div(
    [
        fac.AntdTable(
            locale='en-us',
            columns=[
                {
                    'title': f'outer-field{i}',
                    'dataIndex': f'outer-field{i}',
                    'width': 400
                }
                for i in range(5)
            ],
            data=[
                {
                    **{
                        f'outer-field{j}': i
                        for j in range(5)
                    },
                    'key': f'row-{i}',
                    'children': [
                        {
                            **{
                            f'outer-field{j}': f'child-{i}'
                            for j in range(5)
                            },
                            'key': f'row-{i}-child'
                        }
                    ]
                }
                for i in range(10)
            ],
            bordered=True,
            # expandedRowKeyToContent=[
            #     {
            #         'key': f'row-0-child',
            #         'content': html.Div(
            #             fac.AntdTable(
            #                 columns=[
            #                     {
            #                         'title': f'inner-field{i}',
            #                         'dataIndex': f'inner-field{i}',
            #                     }
            #                     for i in range(5)
            #                 ],
            #                 data=[
            #                     {
            #                         f'inner-field{i}': 'test'
            #                         for i in range(5)
            #                     }
            #                 ] * 5,
            #                 bordered=True
            #             ),
            #             style={
            #                 'padding': 5
            #             }
            #         )
            #     }
            #
            # ]
        )
    ],
    style={
        'padding': 50
    }
)


if __name__ == '__main__':
    app.run(debug=True)
`

**Comment by CNFeffery** [comment]
@romakoifman I do not recommend defining nested rows of data directly in the 'data' parameter through the 'children' key-value pair, as this might break some of the logic added by AntdTable to accommodate 'dash', The way I suggest is as follows:

![image](https://github.com/CNFeffery/feffery-antd-components/assets/49147660/1a7eda7d-2df7-4d8b-8ad5-3ed50811c477)

```python
import dash
from dash import html
import feffery_antd_components as fac

app = dash.Dash(__name__)

app.layout = html.Div(
    [
        fac.AntdTable(
            locale='en-us',
            columns=[
                {
                    'title': f'outer-field{i}',
                    'dataIndex': f'outer-field{i}',
                    'width': 400
                }
                for i in range(5)
            ],
            data=[
                {
                    **{
                        f'outer-field{j}': i
                        for j in range(5)
                    },
                    'key': f'row-{i}'
                }
                for i in range(10)
            ],
            bordered=True,
            expandedRowKeyToContent=[
                {
                    'key': 'row-0',
                    'content': html.Div(
                        fac.AntdTable(
                            columns=[
                                {
                                    'title': f'inner-field{i}',
                                    'dataIndex': f'inner-field{i}',
                                }
                                for i in range(5)
                            ],
                            data=[
                                {
                                    f'inner-field{i}': 'test'
                                    for i in range(5)
                                }
                            ] * 5,
                            bordered=True,
                            pagination={
                                'hideOnSinglePage': True
                            }
                        ),
                        style={
                            'padding': 5
                        }
                    )
                },
                *[
                    {
                        'key': f'row-{i}',
                        'content': 'some demo content'
                    }
                    for i in range(1, 20)
                ]
            ]
        )
    ],
    style={
        'padding': 50
    }
)


if __name__ == '__main__':
    app.run(debug=True)

```

**Comment by romakoifman** [comment]
Thank you!
