### ISSUE TITLE
在AntdTable中引入自定义单元格元素后，行监听属性（如selectedRows、recentlySwitchRow等）会报错，进而影响整个组件的正常功能

### ISSUE THREAD

**Issue by insistence** [CNFeffery/feffery-antd-components#97]
详细报错为：Converting circular structure to JSON
    --> starting at object with constructor 'FiberNode'
    |     property 'stateNode' -> object with constructor 'BaseTreeContainer'
    |     property 'props' -> object with constructor 'Object'
    |     ...
    |     property 'operation' -> object with constructor 'Object'
    --- property '_owner' closes the circle

**Comment by CNFeffery** [comment]
@insistence 相关问题已修复，针对类似的行记录返回回调，自动忽略自定义组件字段值，下个rc版本（`0.2.0rc16`）生效

**Comment by insistence** [comment]
好的，谢谢费老师
